
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Aquil Hussain  ## put your name
title: 'Btech Undergraduate(4th year)'  ## your title
location: Sikkim, India


## Social Profiles
facebook: https://www.facebook.com/aquil.hussain.77  ## your facebook account url
github: https://github.com/Aquilll
linkedin: https://www.linkedin.com/in/aquil-hussain-191069109/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
